#! /bin/zsh

PROFILE_STARTUP=false
if [[ "$PROFILE_STARTUP" == true ]]; then
  # http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html
  # # set the trace prompt to include seconds, nanoseconds, script name and line number
  # # This is GNU date syntax; by default Macs ship with the BSD date program, which isn't compatible
  zmodload zsh/datetime
  setopt promptsubst
  PS4='+$EPOCHREALTIME %N:%i> '
  # # save file stderr to file descriptor 3 and redirect stderr (including trace
  # # output) to a file with the script's PID as an extension
  # exec 3>&2 2>/tmp/startlog.$$
  # # set options to turn on tracing and expansion of commands contained in the prompt
  # PS4=$'%D{%M %S%.} %N:%i> '
  exec 3>&2 2>/tmp/startlog.$$
  setopt xtrace prompt_subst
fi

# increase limits
# ulimit -n 65536
# ulimit -u 2048

autoload -U zmv zcp
ZSH=$HOME/.oh-my-zsh
export ZSH_THEME="robbyrussell"
HISTIGNORE="clear:bg:fg:cd:cd -:exit:date:w:* --help:kill:kill *:touch *:git checkout -- *"
setopt HIST_IGNORE_ALL_DUPS

# plugins
export plugins=(
  git
  zsh-per-directory-history
  osx
  ssh-agent
  git-extras
  golang
  history
  history-substring-search
  extract
  docker
  aws
)

# source "$ZSH/oh-my-zsh.sh"
# don't cd into a directory just because you typed its name - needs to come after sourcing
unsetopt auto_cd

# export PROMPT='%D{%m-%d %L:%M:%S} ${ret_status} %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)'

# Paths
export GOPATH="$HOME/go"
# source "$GOPATH/src/github.com/sheeley/infrastructure/config/zsh_path"
# source "$GOPATH/src/github.com/sheeley/infrastructure/config/aliases"

mkcd() {
  mkdir -p "$1" && cd "$1" || return 1
}

if [[ "$PROFILE_STARTUP" == true ]]; then
  # turn off tracing
  unsetopt xtrace
  exec 2>&3 3>&-
fi
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
