#! /usr/bin/env bash
set -eu

PATH="$PATH:./bin"

HN=$(hostname_wrapper)

VALID_HOSTNAMES=$(get-flake-configurations)

if [[ ! "${VALID_HOSTNAMES[*]}" =~ $HN ]]; then
	echo "invalid hostname: '$HN'"
	echo "sudo scutil --set LocalHostName ..."
	exit 1
fi

echo "rebuild"
OS=$(uname -a)
if [[ "$OS" == *"Darwin"* ]]; then
	./result/sw/bin/darwin-rebuild --rollback switch --flake path:.
else
	sudo nixos-rebuild --rollback switch --flake path:.
fi

date >last-applied.txt
