---
source_directories:
  - ~/projects
  - ~/Documents
  - @storagePath/Music
  - @storagePath/Movies
  - @storagePath/Photos
  - @storagePath/TV
  - @storagePath/Videos

repositories:
  - path: @storagePath@/borgbackup
    label: local
  - path: "ssh://@user@@@user@.repo.borgbase.com/./repo"
    label: remote

exclude_patterns:
  - "*.pyc"
  - ~/*/.cache
  - ~/.cache/*
  - /var/cache/*
  - /var/tmp/*
  - "*.nzb"
  - "*.url"
  - "*.webloc"
  - Thumbs.db
  - .fseventsd*
  - "Apple Music/*"
  - "**/.*.swp"
  - "**/.DS_Store"
  - "**/.VolumeIcon.icns"
  - "**/.DocumentRevisions-V100/"
  - "**/.MobileBackups/"
  - "**/.MobileBackups.trash/"
  - "**/.Spotlight-V100/"
  - "**/.TemporaryItems/"
  - "**/.Trash/"
  - "**/.Trashes/"
  - "**/.build/*"

exclude_if_present: 
  - .nobackup
one_file_system: true

compression: auto,zstd
archive_name_format: "johnny-{now}"
encryption_passphrase: "@secret@"
extra_borg_options:
  create: --list --filter AME

keep_daily: 7
keep_weekly: 4
keep_monthly: 12
keep_yearly: 10

check_last: 3
check_repositories:
  - @storagePath@/borgbackup
checks:
  - name: data
    frequency: 1 month
  - name: repository
    frequency: 2 weeks

before_backup:
  - echo "`date` - Starting backup"

after_backup:
  - echo "`date` - Finished backup"

before_check:
  - echo "`date` - starting checks"

after_check:
  - echo "`date` - finished checks"
