#! /usr/bin/env bash
set -eu pipefail
# set -x

if [ "$(id -u)" -ne 0 ]; then
	echo Please run this script as root or using sudo!
	exit
fi

mkdir -p /etc/backup

cp -f ./*.service ./*.timer /etc/systemd/system/
cp -f ./resolved.yaml /etc/backup/borgmatic.yaml
cp -f ./backup ./send-notification /bin/

systemctl daemon-reload
