#! /usr/bin/env bash
set -eux pipefail

if [ "$(id -u)" -ne 0 ]; then
	echo Please run this script as root or using sudo!
	exit
fi

mkdir -p /etc/backup

# link systemd files
cp -f ./*.service ./*.timer /etc/systemd/system/
cp -f ./borgmatic.yaml /etc/backup
cp -f ./backup /bin/backup

# ensure they're running
systemctl daemon-reload
