#! /usr/bin/env bash
set -euo pipefail
set -x
# TODO: mas account https://github.com/mas-cli/mas/issues/417

IDS=(
	1569813296 # "1Password Safari"
	1586435171 # "Actions"
	937984704  # "Amphetamine"
	1056643111 # "Clocker"
	913158085  # "Expressions"
	775737590  # "iA Writer"
	1622835804 # "Kagi"
	441258766  # "Magnet"
	429449079  # "Patterns"
	1554235898 # "Peek"
	1611378436 # "Pure Paste"
	1529448980 # "Reeder"
	1626843895 # "Remove Web Limits"
	693112260  # "Sim Daltonism"
	425424353  # "The Unarchiver"
	734258109  # "Watchdog"
	497799835  # "Xcode"
	1611554653 # "Logger for Shortcuts"
)

mas install "${IDS[@]}"

open_if_not_running() {
	if ! pgrep -q -f "$1"; then
		open -j "$1"
	fi
}

# Ensure these are opened at least once to get services set up
open_if_not_running /Applications/Amphetamine.app/
open_if_not_running /Applications/Magnet.app/
