
defaults write com.googlecode.iterm2 "Normal Font" -string "FiraMonoNFM-Regular 12"
defaults write com.googlecode.iterm2 "Non Ascii Font" -string "Monaco 12"
defaults write com.googlecode.iterm2 "PromptOnQuit" -boolean false
defaults write com.googlecode.iterm2 "SUEnableAutomaticChecks" -boolean true
defaults write com.googlecode.iterm2 "SoundForEsc" -boolean false
defaults write com.googlecode.iterm2 "VisualIndicatorForEsc" -boolean true


defaults write com.googlecode.iterm2 "GlobalKeyMap" '
    <dict>
    <key>0x19-0x60000</key>
    <dict>
        <key>Action</key>
        <integer>39</integer>
        <key>Text</key>
        <string></string>
    </dict>
    <key>0x50-0x120000-0x23</key>
    <dict>
        <key>Action</key>
        <integer>12</integer>
        <key>Label</key>
        <string></string>
        <key>Text</key>
        <string>:Telescope commands\n</string>
        <key>Version</key>
        <integer>1</integer>
    </dict>
    <key>0x70-0x100000-0x23</key>
    <dict>
        <key>Action</key>
        <integer>12</integer>
        <key>Label</key>
        <string></string>
        <key>Text</key>
        <string>:Telescope find_files\n</string>
        <key>Version</key>
        <integer>1</integer>
    </dict>
    <key>0x9-0x40000</key>
    <dict>
        <key>Action</key>
        <integer>32</integer>
        <key>Text</key>
        <string></string>
    </dict>
    <key>0xf700-0x300000</key>
    <dict>
        <key>Action</key>
        <integer>7</integer>
        <key>Text</key>
        <string></string>
    </dict>
    <key>0xf701-0x300000</key>
    <dict>
        <key>Action</key>
        <integer>6</integer>
        <key>Text</key>
        <string></string>
    </dict>
    <key>0xf702-0x300000</key>
    <dict>
        <key>Action</key>
        <integer>2</integer>
        <key>Text</key>
        <string></string>
    </dict>
    <key>0xf702-0x320000</key>
    <dict>
        <key>Action</key>
        <integer>33</integer>
        <key>Text</key>
        <string></string>
    </dict>
    <key>0xf703-0x300000</key>
    <dict>
        <key>Action</key>
        <integer>0</integer>
        <key>Text</key>
        <string></string>
    </dict>
    <key>0xf703-0x320000</key>
    <dict>
        <key>Action</key>
        <integer>34</integer>
        <key>Text</key>
        <string></string>
    </dict>
    <key>0xf729-0x100000</key>
    <dict>
        <key>Action</key>
        <integer>5</integer>
        <key>Text</key>
        <string></string>
    </dict>
    <key>0xf72b-0x100000</key>
    <dict>
        <key>Action</key>
        <integer>4</integer>
        <key>Text</key>
        <string></string>
    </dict>
    <key>0xf72c-0x100000</key>
    <dict>
        <key>Action</key>
        <integer>9</integer>
        <key>Text</key>
        <string></string>
    </dict>
    <key>0xf72c-0x20000</key>
    <dict>
        <key>Action</key>
        <integer>9</integer>
        <key>Text</key>
        <string></string>
    </dict>
    <key>0xf72d-0x100000</key>
    <dict>
        <key>Action</key>
        <integer>8</integer>
        <key>Text</key>
        <string></string>
    </dict>
    <key>0xf72d-0x20000</key>
    <dict>
        <key>Action</key>
        <integer>8</integer>
        <key>Text</key>
        <string></string>
    </dict>
    </dict>
    '